apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-stats-measurements-chart.backendName" . }}
spec:
  selector:
    app: {{ include "ai-stats-measurements-chart.backendName" . }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
  type: {{ .Values.backend.service.type }}