apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-stats-measurements-chart.frontendName" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ai-stats-measurements-chart.frontendName" . }}
  template:
    metadata:
      labels:
        app: {{ include "ai-stats-measurements-chart.frontendName" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 8080