apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-stats-measurements-chart.frontendName" . }}
spec:
  selector:
    app: {{ include "ai-stats-measurements-chart.frontendName" . }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  type: {{ .Values.frontend.service.type }}