// <auto-generated />
using System;
using System.Collections.Generic;
using AI_stats_measurement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI_stats_measurement.Backend.Migrations
{
    [DbContext(typeof(AIMeasureDbContext))]
    [Migration("20260420121322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI_stats_measurement.Backend.Models.ExportRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualAnswer")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<List<int>>("ActualSource")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("AnswerIsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<decimal>("ExpectedAnswer")
                        .HasColumnType("numeric");

                    b.Property<string>("ExpectedSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.Property<decimal>("RelativeError")
                        .HasColumnType("numeric");

                    b.Property<bool>("SourceIsCorrect")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SquareMeanRootError")
                        .HasColumnType("numeric");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExportRows");
                });

            modelBuilder.Entity("AI_stats_measurement.Backend.Models.ParsedModelResponseSource", b =>
                {
                    b.Property<int>("ParsedModelResponseId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.HasKey("ParsedModelResponseId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("ParsedModelResponseSources");
                });

            modelBuilder.Entity("AI_stats_measurement.Backend.Models.PromptDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromptId", "Name")
                        .IsUnique();

                    b.ToTable("PromptDimensions");
                });

            modelBuilder.Entity("AI_stats_measurement.Backend.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Url")
                        .IsUnique();

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("AI_stats_measurement.Models.ModelResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<int>("PromptId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("ModelResponses");
                });

            modelBuilder.Entity("AI_stats_measurement.Models.ParsedModelResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Answer")
                        .HasColumnType("numeric");

                    b.Property<int>("ModelResponseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelResponseId")
                        .IsUnique();

                    b.ToTable("ParsedModelResponses");
                });

            modelBuilder.Entity("FactCheckResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbsoluteError")
                        .HasColumnType("numeric");

                    b.Property<bool>("Abstained")
                        .HasColumnType("boolean");

                    b.Property<bool>("AnswerIsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("ParsedModelResponseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RelativeError")
                        .HasColumnType("numeric");

                    b.Property<bool>("SourceIsCorrect")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParsedModelResponseId")
                        .IsUnique();

                    b.ToTable("FactCheckResults");
                });

            modelBuilder.Entity("Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Answer")
                        .HasColumnType("numeric");

                    b.Property<string>("AnswerLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Periode")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("AI_stats_measurement.Backend.Models.ParsedModelResponseSource", b =>
                {
                    b.HasOne("AI_stats_measurement.Models.ParsedModelResponse", "ParsedModelResponse")
                        .WithMany("ParsedModelResponseSources")
                        .HasForeignKey("ParsedModelResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI_stats_measurement.Backend.Models.Source", "Source")
                        .WithMany("ParsedModelResponseSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParsedModelResponse");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AI_stats_measurement.Backend.Models.PromptDimension", b =>
                {
                    b.HasOne("Prompt", "Prompt")
                        .WithMany("Dimensions")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AI_stats_measurement.Models.ModelResponse", b =>
                {
                    b.HasOne("Prompt", "Prompt")
                        .WithMany("ModelResponses")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AI_stats_measurement.Models.ParsedModelResponse", b =>
                {
                    b.HasOne("AI_stats_measurement.Models.ModelResponse", "ModelResponse")
                        .WithOne("ParsedResponse")
                        .HasForeignKey("AI_stats_measurement.Models.ParsedModelResponse", "ModelResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelResponse");
                });

            modelBuilder.Entity("FactCheckResult", b =>
                {
                    b.HasOne("AI_stats_measurement.Models.ParsedModelResponse", "ParsedModelResponse")
                        .WithOne("FactCheckResult")
                        .HasForeignKey("FactCheckResult", "ParsedModelResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParsedModelResponse");
                });

            modelBuilder.Entity("Prompt", b =>
                {
                    b.HasOne("AI_stats_measurement.Backend.Models.Source", "Source")
                        .WithMany("Prompts")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AI_stats_measurement.Backend.Models.Source", b =>
                {
                    b.Navigation("ParsedModelResponseSources");

                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("AI_stats_measurement.Models.ModelResponse", b =>
                {
                    b.Navigation("ParsedResponse");
                });

            modelBuilder.Entity("AI_stats_measurement.Models.ParsedModelResponse", b =>
                {
                    b.Navigation("FactCheckResult");

                    b.Navigation("ParsedModelResponseSources");
                });

            modelBuilder.Entity("Prompt", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("ModelResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
